env:
  global:
    - CC_TEST_REPORTER_ID=546a512515094a1117bf1b4558feb4427e514f3dbbe00f73387d0d944d1802d3

language: node_js

node_js:
  - "10"

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# Pipe the coverage data to Code Climate
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT